main: main.o biblio.o
	gcc -o main main.o biblio.o

q5: q5.o biblio.o
	gcc -o q5 q5.o biblio.o

q5.o: q5.c
	gcc -c q5.c

partie2: partie2.o biblio.o
	gcc -o partie2 partie2.o biblio.o

main.o: main.c
	gcc -c main.c

biblio.o: biblio.c
	gcc -c biblio.c

